name: simple_to_do_app
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.0+1
environment:
  sdk: ^3.4.4

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  cupertino_icons: ^1.0.6
  intl: any
  uuid: ^4.4.2
  flutter_bloc: ^8.1.6
  equatable: ^2.0.5
  shared_preferences: ^2.3.1
  get_it: ^8.0.2
  google_fonts: ^6.2.1
  lottie: ^3.1.3
  firebase_core: ^3.8.0
  firebase_crashlytics: ^4.1.5
  firebase_analytics: ^11.3.5
  flutter_local_notifications: ^18.0.1
  timezone: ^0.10.0
  envied: ^1.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  integration_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  bloc_test: ^9.1.7
  mocktail: ^1.0.4
  fake_async: 1.3.1
  flutter_launcher_icons: ^0.14.1
  envied_generator: ^1.0.0
  build_runner: ^2.4.13

flutter_icons:
  image_path: "assets/icon.png"
  android: true

flutter:
  uses-material-design: true
  generate: true

  assets:
    - assets/

